[package]
name = "ruskey"
version = "0.1.0"
authors = ["Robert Gmyr <robert@gmyr.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
